
<script>
	import { base } from '$app/paths';
</script>

<!-- Generated by ai2html v0.120.0 - 2024-04-22 09:15 -->
<!-- ai file: jokes_and_structure_img.ai -->
<style media="screen,print">
	#g-jokes_and_structure_img-box ,
	#g-jokes_and_structure_img-box .g-artboard {
		margin:0 auto;
	}
	#g-jokes_and_structure_img-box p {
		margin:0;
	}
	#g-jokes_and_structure_img-box .g-aiAbs {
		position:absolute;
	}
	#g-jokes_and_structure_img-box .g-aiImg {
		position:absolute;
		top:0;
		display:block;
		width:100% !important;
	}
	#g-jokes_and_structure_img-box .g-aiSymbol {
		position: absolute;
		box-sizing: border-box;
	}
	#g-jokes_and_structure_img-box .g-aiPointText p { white-space: nowrap; }
	#g-jokes_and_structure_img-Artboard_1 {
		position:relative;
		overflow:hidden;
	}

</style>

<div id="g-jokes_and_structure_img-box" class="ai2html">

	<!-- Artboard: Artboard_1 -->
	<div id="g-jokes_and_structure_img-Artboard_1" class="g-artboard" style="max-width: 2345px;max-height: 1606px" data-aspect-ratio="1.461" data-min-width="0">
<div style="padding: 0 0 68.4691% 0;"></div>
		<img id="g-jokes_and_structure_img-Artboard_1-img" class="g-jokes_and_structure_img-Artboard_1-img g-aiImg" alt="" src="{base}/jokes_and_structure_img-Artboard_1.png"/>
	</div>

</div>

<!-- End ai2html - 2024-04-22 09:15 -->
