
<!-- Generated by ai2html v0.120.0 - 2024-04-22 11:40 -->
<!-- ai file: segment-visual.ai -->
<style media="screen,print">
	#g-segment-visual-box ,
	#g-segment-visual-box .g-artboard {
		margin:0 auto;
	}
	#g-segment-visual-box p {
		margin:0;
	}
	#g-segment-visual-box .g-aiAbs {
		position:absolute;
	}
	#g-segment-visual-box .g-aiImg {
		position:absolute;
		top:0;
		display:block;
		width:100% !important;
	}
	#g-segment-visual-box .g-aiSymbol {
		position: absolute;
		box-sizing: border-box;
	}
	#g-segment-visual-box .g-aiPointText p { white-space: nowrap; }
	#g-segment-visual-Artboard_1 {
		position:relative;
		overflow:hidden;
	}

</style>

<div id="g-segment-visual-box" class="ai2html">

	<!-- Artboard: Artboard_1 -->
	<div id="g-segment-visual-Artboard_1" class="g-artboard" style="max-width: 2000px;max-height: 1500px" data-aspect-ratio="1.333" data-min-width="0">
<div style="padding: 0 0 75% 0;"></div>
		<img id="g-segment-visual-Artboard_1-img" class="g-segment-visual-Artboard_1-img g-aiImg" alt="" src="/segment-visual-Artboard_1_nojoke.png"/>
	</div>

</div>

<!-- End ai2html - 2024-04-22 11:40 -->
