
<!-- Generated by ai2html v0.120.0 - 2024-04-22 02:31 -->
<!-- ai file: video-sections-combined.svg -->
<style media="screen,print">
	#g-video-sections-combined_svg-box ,
	#g-video-sections-combined_svg-box .g-artboard {
		margin:0 auto;
	}
	#g-video-sections-combined_svg-box p {
		margin:0;
	}
	#g-video-sections-combined_svg-box .g-aiAbs {
		position:absolute;
	}
	#g-video-sections-combined_svg-box .g-aiImg {
		position:absolute;
		top:0;
		display:block;
		width:100% !important;
	}
	#g-video-sections-combined_svg-box .g-aiSymbol {
		position: absolute;
		box-sizing: border-box;
	}
	#g-video-sections-combined_svg-box .g-aiPointText p { white-space: nowrap; }
	#g-video-sections-combined_svg-Artboard_1 {
		position:relative;
		overflow:hidden;
	}

</style>

<div id="g-video-sections-combined_svg-box" class="ai2html">

	<!-- Artboard: Artboard_1 -->
	<div id="g-video-sections-combined_svg-Artboard_1" class="g-artboard" style="max-width: 2345px;max-height: 1606px" data-aspect-ratio="1.461" data-min-width="0">
<div style="padding: 0 0 68.4691% 0;"></div>
		<img id="g-video-sections-combined_svg-Artboard_1-img" class="g-video-sections-combined_svg-Artboard_1-img g-aiImg" alt="" src="/video-sections-combined_svg-Artboard_1.png"/>
	</div>

</div>

<!-- End ai2html - 2024-04-22 02:31 -->
