<script>
    import Slide from '$lib/Slide.svelte';

</script>

<Slide bgColor="#8db3cf">
    <div class="content">
        <p class="sticky">This is the transcript for the entire episode.</p>

        <p class="transcript">
            <span class="caption Lede" data-start="00:00:04:11">We're going to dive straight into our main story tonight,  which concerns the death penalty. America's had it for centuries,  but its methods have varied considerably as this documentary from the 80s  explains in weirdly comprehensive fashion.</span>
            <span class="caption Source" data-start="00:00:17:07">The methods America has used to execute  its criminals have changed over the years. From burning to drawing and quartering  to hanging. Criminals have been axed,  crucified, buried alive, pressed with weights, stoned, impaled, starved, decapitated,   and gibbetted. Gibetting was the hanging of the condemned man  by chains to rot. Death often takes weeks to occur.</span>
            <span class="caption Joke" data-start="00:00:45:21">Holy shit. A few things. First, if that list wasn't so horrifying,  the creativity would be genuinely impressive. I mean, pressed with weights? You've got to be pretty inventive to be brainstorming ways to kill people  and think ‚ÄòLet's panini them‚Äô. Second, what the fuck is axed? At first I thought, well, it's beheading,  but then decapitated is listed as its own thing. So is axed just someone hacking at you  like one of those lumberjack competitions? Or did people just throw axes  like they're in a bachelorette party in Brooklyn that needed an activity  and asked to give it to him? And as for gibbetting, that is a horrifying definition  for an adorable word. Gibbetting sounds like what you call  baby goats rushing to food at a petting zoo. Or the weird head movement that pigeons make. At its grossest, gibbetting should be  when you have the hiccups but there's a tiny bit of throw up in it, not hanging someone by chains  for days until they rot to death.</span>
            <span class="caption Recap" data-start="00:01:40:12">Let me just acknowledge,  we've talked about the death penalty before in our second  ever show back in 2014 and again</span>
            <span class="caption Joke" data-start="00:01:47:07">five years later in an episode narrowly  beating out Paul Blart Mall Cop 2 as the least anticipated  sequel of all time.</span>
            <span class="caption Recap" data-start="00:01:55:13">And to quickly  summarize the arguments in those stories, our stance was that the death  penalty is morally wrong, there is no humane way to do it,  and any discussion of one</span>
            <span class="caption Joke" data-start="00:02:03:22">is akin to coming up with the best way  to fuck your mom, which is to say there's simply no right way to do that.</span>
            <span class="caption Nutgraf" data-start="00:02:10:17">But we need to talk about the death  penalty a third time tonight because there have been some grim  developments For one thing, since our last piece aired, the US has executed  91 people and 13 of those executions were done at the federal level,  which is actually unusual given that for almost two decades there had been zero  and all those 13 federal executions were under Trump, who went on an execution  spree at the end of his term, including the first lame duck  federal execution in more than a century.</span>
            <span class="caption Explanation" data-start="00:02:39:05">Which really shouldn't be surprising given his outspoken love of capital punishment from taking out  full page ads calling for it to be applied to the Central Park Five,  to constantly saying things like this:</span>
            <span class="caption Source" data-start="00:02:50:21">I've always supported the death penalty. I don't even understand  people that don't. Death penalty bring it forth. I am so for the death penalty. Remember the old days, a deserter, what happened? Bang. You know, the old days, boom, firing squad. You know, the old days bing bong. When we were strong. When we were strong. The ultimate penalty has to be the death penalty. Now maybe our country's not ready for that. It's possible. It's possible, that our country's not ready for that. And I can understand it. Maybe. Although personally I can't understand that.</span>
            <span class="caption Joke" data-start="00:03:28:00">Okay. First,  genuinely shocking to hear the phrase bring it forth come out of his mouth. Second, how can you understand  but also can't understand? And finally, do you think guns go bing bong? Why would you make that sound  when there are so many correct gun noises? Bang, boom, pew, pow. I'd even accept blamo, but bing bong? The fuck are you talking about? I guess what I'm trying to say is  I can understand it. Maybe.  Although personally, I can't understand it.</span>
            <span class="caption Thesis" data-start="00:03:59:04">But the thing I want to focus on  about those federal executions is the method used to carry them out  because it wasn't 100% by the book. And that probably shouldn't be surprising, coming from the Trump administration. But we may have some new information  for you tonight about exactly how far from the book  they ended up straying. And that disregard  speaks to a larger issue here, which is that our federal and state  governments have continued to pursue questionably legal  and definitely horrifying ways to do something that, again, I would argue  they shouldn't be doing at all. So given that tonight, let's check in on some of the new ways  our government has found to execute people.</span>
            <span class="caption Point" data-start="00:04:34:05">And let's start with the fact  that, as we've discussed before, it can be incredibly hard for the government  to find drugs to use in lethal injections.</span>
            <span class="caption Source" data-start="00:04:41:11">The governor of South Carolina once summed up the reason for that  at a press conference to explain why a planned lethal injection  couldn't actually be carried out. The reason we don't have the drugs,  despite efforts, intense efforts to get them, is because the companies  that make them, the distributors who distribute them, and the pharmacies  who may have to compound them don't want to be identified. They are afraid that their names  will be made known and they don't want to have anything  to do with it.</span>
            <span class="caption Explanation" data-start="00:05:11:05">He's right.</span>
            <span class="caption Joke" data-start="00:05:12:02">He's doing a B-minus impression  of Foghorn Leghorn, but he is right.</span>
            <span class="caption Explanation" data-start="00:05:16:00">Drug suppliers don't want their names  associated with executions. In fact, people generally don't like to be associated  with killing their fellow citizens.</span>
            <span class="caption Joke" data-start="00:05:23:10">This is why your friend's husband says he's in consulting  instead of working for big tobacco. And Becca from college  says she's a corporate lawyer instead of defending the sackless  in court. Also, and this isn't the point,  but did these two coordinate their outfits? I'm going to choose to believe that the governor called up the other guy  the night before and was like,  hey, babe, let's do red tie white shirt and an untailored black suit from Joseph A Bank‚Äôs  Drab conservative collection. See you in the morning twinsy.</span>
            <span class="caption Point" data-start="00:05:51:00">What that governor was pushing for and ultimately got was a shield law keeping  the names of drug suppliers secret.</span>
            <span class="caption Source" data-start="00:05:58:23">And South Carolina isn't alone  there. Since 2011, 15 states have enacted new secrecy statutes  that conceal vital information about the execution process, from the names of drug suppliers  to the identities of those participating.</span>
            <span class="caption Point" data-start="00:06:12:03">But even with that secrecy,  many suppliers still refuse to provide drugs for executions  because it's bad for business.</span>
            <span class="caption Point" data-start="00:06:20:01">And that has led states to source drugs  from some pretty sketchy suppliers, which is a problem because when drugs are  tainted or not formulated at the proper dosage, executions become a protracted  nightmare of suffering, which is both horrifying  and also unconstitutional.</span>
            <span class="caption Source" data-start="00:06:35:20">Take Arizona. Over the years, it sourced drugs from places,  including a driving school in London and a random guy in India  whose supposed facilities included his former apartment  and whose drugs were seized by the FDA. And Arizona has a history  of not administering drugs properly, actually paused executions for eight years  after one in 2014 was botched, taking nearly 2 hours  as a man died gasping for air.</span>
            <span class="caption Point" data-start="00:07:01:20">And when executions resumed, there  a couple of years ago, there was a concern  they'd repeat those mistakes. But the state's A.G., Mark Brnovich, didn't  seem not concerned about any of this.</span>
            <span class="caption Source" data-start="00:07:11:19">But at the end of the day,  what these killers get with lethal injection is much better than anything  they did to the victims and their families.</span>
            <span class="caption Point" data-start="00:07:20:06">Okay. But that doesn't really matter, does it? Because the Constitution exists.</span>
            <span class="caption Joke" data-start="00:07:25:14">The Eighth Amendment doesn't say no  cruel and unusual punishment unless they, like, really deserve it.</span>
            <span class="caption Point" data-start="00:07:32:17">Now, interestingly,  there's been a big development in lethal injections, with states  increasingly giving up on the method Many had been using,  a three drug cocktail of an anesthetic, a paralytic, and a drug  that induces cardiac arrest, a process that's been likened to being paralyzed  while fire is poured into your veins. Instead, they switched over to a single massive  shot of a sedative called pentobarbital. That is the drug the Trump administration  used in its end of term killing spree. But it is no less brutal  than the other method, because while the Trump administration  offered sanitized accounts of the executions it carried out,  likening the process to falling asleep, calling the gurneys "beds"  and the final breaths "snores",</span>
            <span class="caption Source" data-start="00:08:13:08">witnesses report that prisoners  stomachs rolled, shook and shuddered as the pentobarbital took effect. And in the two autopsies done  after those execution, both revealed that inmates lungs were twice  as heavy as they should be, indicating pulmonary edema,  where fluid rushes into lungs and airways, which,  if you're not properly anesthetized, could cause pain akin  to being suffocated or drowned.</span>
            <span class="caption Explanation" data-start="00:08:35:11">All of which is about as far from  peacefully falling asleep in your bed</span>
            <span class="caption Joke" data-start="00:08:39:21">as your kid's dog is  from chasing cars in doggy heaven. That person suffered and that dog is dead and in doggy hell  because he was never baptized.</span>
            <span class="caption Point" data-start="00:08:51:03">But even setting the brutality  aside, a key question hanging over this whole thing is where exactly did  the Trump administration get these drugs? Because it's not like it's easy  to find a supplier willing to sell you pentobarbital. You can't just pop into CVS</span>
            <span class="caption Joke" data-start="00:09:06:12">and head over to the state  sponsored execution drugs aisle.</span>
            <span class="caption Source" data-start="00:09:10:07">Tennessee's Department of Corrections  spent years trying to find pentobarbital for its executions. Reports later exposed the lengths it was  willing to go to, to find a supplier. Emails between TDOC and the pharmacy  they work with revealed the agency was looking at importing  the drug from a different country. Years earlier,  TDOC had even asked the pharmacy if they could get the drug  through a veterinarian. But it didn't work out. You don't get drugs  that you give to animals, to people. It is sort of ridiculous  that we have to run around the country begging and borrowing for drugs  to kill people.</span>
            <span class="caption Explantion" data-start="00:09:45:14">Right. The D.O.C. shouldn't be running around the country  begging for drugs.</span>
            <span class="caption Joke" data-start="00:09:50:13">That is, for diabetics and women who want  to exercise their right to choose. This is America.</span>
            <span class="caption Explantion" data-start="00:09:56:20">And he's right. You shouldn't give animal drugs to people. We probably shouldn't be ingesting</span>
            <span class="caption Joke" data-start="00:10:02:07">anything meant for animals, aside  from maybe, fancy feast, because be honest, tell me  that doesn't look good. I know it's just a wet puddle  of chicken for cats, but frankly, I'm interested.</span>
            <span class="caption Point" data-start="00:10:16:11">So pentobarbital is hard to find, raising the question of again,  where the Trump administration got it. But that is hard to find out  because at every level, those who carry out executions  crave secrecy.</span>
            <span class="caption Source" data-start="00:10:29:07">When South Carolina's execution  methods were challenged in the state Supreme Court, here's the argument the state made for why  some elements of their process had to remain secret. Your honor, the minute you begin  to disclose anything about the drug, you begin to give the other side puzzle pieces  as to where the drug came from. So whether it's manufactured  or compounded, what's the lot number of the drug or the bulk material, as you begin to piece  together who manufactured it, where could it have been compounded, who could have sold them the bulk material, and the minute you start releasing that you make it harder for SCDC  to get the drugs in the future.</span>
            <span class="caption Explanation" data-start="00:11:03:14">Now, that is an interesting point.</span>
            <span class="caption Joke" data-start="00:11:05:06">Even if it is coming from  Team Sheldon, super lawyer.</span>
            <span class="caption Explanation" data-start="00:11:09:04">Any time you unmask a drug supply, that probably  is going to make carrying out executions much harder. So you can see why the federal government  so badly wants to keep its supply a secret too.</span>
            <span class="caption Point" data-start="00:11:19:18">And that is why  it might be slightly inconvenient for them that we're pretty sure we've tracked down exactly  who supplied the Trump administration with its pentobarbital. It's a company called Absolute Standards  based in Hamden, Connecticut. That is their logo on the sign outside,  which is presumably supposed</span>
            <span class="caption Joke" data-start="00:11:36:08">to be a chemical particle, even though it looks more like a mobile  made out of minion testicles.</span>
            <span class="caption Point" data-start="00:11:41:23">Absolute Standards  business is making chemicals for calibrating machines, which is to say,  not making drugs for human consumption. But we're pretty sure they're making  execution drugs as a side hustle. And I think our case is pretty strong.</span>
            <span class="caption Joke" data-start="00:11:54:05">And I know I've spent a lot of time  over the last ten years reassuring everyone that this show does  comedy and not journalism, but I think we can all agree that the most important thing we do  here is stir shit up.</span>
            <span class="caption Explanation" data-start="00:12:05:07">And it's in that spirit  that I want to explain how we got to this point,  because one of our researchers has been covering the death penalty  for years,</span>
            <span class="caption Source" data-start="00:12:12:20">long before he worked for us,  and he found that Absolute Standard had registered with the DEA to produce  pentobarbital in August of 2018. And as it happens, when the Bureau of Prisons was asked  when it entered into a contract with a new pentobarbital supplier, they said  it would have been roughly August of 2018. So the timeline matches up.</span>
            <span class="caption Explanation" data-start="00:12:32:13">And I will say we're not the first  to suspect this company.</span>
            <span class="caption Source" data-start="00:12:35:08">Reuters asked similar questions  a few years ago, and the lab's director initially said his company  had no involvement with the government's execution drugs, only to later say  he could not rule it out because in many parts of our market,  we don't know what the final intended use is going to be,  which isn't that reassuring.</span>
            <span class="caption Joke" data-start="00:12:52:06">It is one thing if you're a peanut farmer  and you don't know if your nuts are going to be used in trail  mix or the nipples on a snowman. Everyone knows you use coal for the eyes, a carrot for the nose and peanuts  for the nipples. I don't make the rules. I just follow them.</span>
            <span class="caption Point" data-start="00:13:09:16">But for a manufacturer of drugs  that kill people, you should probably know  where your products are going,</span>
            <span class="caption Explanation" data-start="00:13:14:21">but we still weren't entirely sure.</span>
            <span class="caption Source" data-start="00:13:16:06">So we filed a Freedom of Information Act  request or FOIA, with the DEA back in 2020 asking for any records  they had on Absolute Standards. And while we were waiting for them  to send us over the documents, the agency's  liaison slipped up twice over the phone and told us that the reason  the request was taking so long was because the documents  were related to the death penalty,</span>
            <span class="caption Joke" data-start="00:13:37:10">which is what's known in the government  world as a big old whoopsie. And honestly, five out of five on the post call survey  there, this employee certainly helped me solve my problem.</span>
            <span class="caption Source" data-start="00:13:50:03">And on top of all this, a confidential source our researcher trusts has now confirmed that Absolute Standards  is the company who made the drug.</span>
            <span class="caption Explanation" data-start="00:13:57:11">So it's them, it's Absolute Standards.</span>
            <span class="caption Joke" data-start="00:14:01:15">Honestly, at this point, they might as well just update their  real slogan of we have the solutions, to we have the solutions that were secretly  used in a bunch of government executions It even rhymes. You can have that slogan for free  you monsters.</span>
            <span class="caption Point" data-start="00:14:14:06">Look, maybe Absolute  Standards is proud to be producing the drugs that enabled our government  to effectively drown at least 13 people  while they were strapped to a table. I don't know.</span>
            <span class="caption Explanation" data-start="00:14:22:04">We've reached out to them repeatedly for comment on the story  and they have ignored us, which is an odd thing to do when someone's  accusing you of making execution drugs.</span>
            <span class="caption Point" data-start="00:14:30:22">But even if they are happy to keep doing  this, it's not clear whether they should be able to,  because under the law, companies that make drugs  need to be registered with the FDA. And the Trump administration claimed  before the executions</span>
            <span class="caption Source" data-start="00:14:43:17">that its supply was properly registered. But remember, Absolute Standards  doesn't make drugs for human consumption. So we filed another FOIA  request with the FDA asking for records they had related to Absolute Standards,  and they responded by saying they were unable to locate any records  responsive to your request. And the firm has not been inspected by the FDA,  which is basically government jargon for</span>
            <span class="caption Joke" data-start="00:15:06:02">who the fuck is Absolute Standards  and what the fuck are you asking us about?</span>
            <span class="caption Point" data-start="00:15:11:09">So Absolute Standards  aren't just making execution drugs. I'd argue they're doing so illegally.</span>
            <span class="caption Point" data-start="00:15:17:06">And it turns out  it's not just the federal government that's been buying drugs from them, because when the Trump administration  restarted federal executions, Arizona's A.G. Mark  Brnovich asked them for help.</span>
            <span class="caption Source" data-start="00:15:26:22">And his state wound up spending an incredible one  and a half million dollars of taxpayer money to have 1000 vials of pentobarbital  delivered in unmarked jars and boxes.</span>
            <span class="caption Joke" data-start="00:15:37:03">The official packaging of things  you shouldn't be shipping. And I get wanting secrecy,  but you got to put something on those jars to warn people they might be dangerous. At least slap on a sticker like a bunny with crossed out eyes or a weirdly buff  Michael Cera. Something that makes you go,  I don't trust what's in this thing.</span>
            <span class="caption Source" data-start="00:15:58:16">And our source told us that  the supply in that instance was again, Absolute Standards,  which for all we know, could well still be selling those drugs  to any state that wants them.</span>
            <span class="caption Point" data-start="00:16:07:18">And if those unmarked jars did  come from a company without FDA approval, which they did, it  sort of calls into question a promise that Brnovich made the last time  his state was caught buying drugs from questionable sources.</span>
            <span class="caption Joke" data-start="00:16:20:09">Eight years and one beard ago.</span>
            <span class="caption Source" data-start="00:16:23:00">all I can assure you  is that as long as I'm Attorney General, we will follow all state  and federal regulations and all state and federal laws  when it comes to obtaining and using the drugs  in the executions here in Arizona.</span>
            <span class="caption Explanation" data-start="00:16:35:11">Yeah, but it turns out maybe not. And as long as he was making promises</span>
            <span class="caption Joke" data-start="00:16:39:03">he wasn't going to keep,  he might as well have added I can also assure you  that I will never grow a beard. That makes me look like  Ted Cruz's less hot cousin.</span>
            <span class="caption Point" data-start="00:16:47:05">Now, Brnovich maintains  Arizona didn't have to follow drug laws because the DOJ issued a legal opinion  that the FDA has no jurisdiction over drugs  intended for use in lawful executions. And it is true that during the Trump  administration, under Bill Barr, the DOJ did write that opinion,  and that memo prohibits the FDA from taking action against a company  making unregulated drugs for executions. But the federal appeals court in D.C. has repeatedly ruled, both before  and after that memo was written, that drug laws still apply when they're used  for lethal injections, meaning they essentially found  the central argument of Barr's memo to be complete horseshit,  which does make sense because think about</span>
            <span class="caption Explanation" data-start="00:17:26:17">what Brnovich and Barr are arguing there,   they're saying that the company that wouldn't be qualified  to make drugs to euthanize animals is perfectly qualified  to make drugs, to kill human beings. It's a pretty embarrassing argument  for a state A.G. to even try to make,</span>
            <span class="caption Joke" data-start="00:17:40:06">although I will say  it's not the most embarrassing thing that he has ever done, considering he's  also a self-described nunchuck enthusiast who once did this. It's Arizona  Attorney General Mark Brnovich. We've gotten a lot of calls,  a lot of emails, but there's one thing  people definitely want to see. They want to see more chucks. You want more chucks? You got more chucks. Cool. Just to be clear, Mark, at  no point did I say I wanted more chucks and I've never hoped so hard that someone was about to accidentally  chuck themselves in the dick.</span>
            <span class="caption Point" data-start="00:18:27:15">Now, thankfully, Arizona's current  governor has paused executions there, pending a review of the transparency,  accountability, and safety of the execution process. Let me just say, governor, I have some notes on where  you might want to begin asking questions.</span>
            <span class="caption Joke" data-start="00:18:41:02">It's right here on Google Maps. If you have the cheese manufacturer,  you've gone too far. Also, if you work at Absolute  Standards, you've gone too far. But that is a different issue.</span>
            <span class="caption Point" data-start="00:18:50:15">But the truth is, even if we shut down the use of pentobarbital  it won't stop executions in this country.</span>
            <span class="caption Source" data-start="00:18:56:05">Because elected leaders seem hell bent on  getting it done. In South Carolina. where you saw the governor bemoaning their difficulty in sourcing  execution drugs, his outfit doppelganger, the head of their prison system  at one point noted they could just fall back  on the electric chair instead and just watch as a local interviewer  starts spitballing other alternatives for him as well. If lethal injection is not available,  then it defaults to the electric chair. Why not? Like I mean, it's even fentanyl. I mean, that's such it's  been been such a horrible drug for so many people  and it obviously is very widely available. But even something like that, you  couldn't get? No one would sell it to us. Anytime we have a conversation with people  about trying to find it, trying to compound it, people just say,  I'm not going to give it to you for that. Can you guys just take it from evidence  over one of these county sheriff's office There'd be a  there'd be a constitutional claim there. And that's just too dan- You can't do that.</span>
            <span class="caption Joke" data-start="00:19:47:23">What are you doing? Honestly, part of me wishes he just kept  throwing out ideas to kill people. Okay, so we can't get fentanyl,  Can we sprinkle prisoners with anthrax? What about throwing  a bunch of poisonous toads at them? What if we drop them into the hippo pool at the zoo  and just let the hippos take care of it? Or you know what? What about gibbetting? I hear that's really good.</span>
            <span class="caption Point" data-start="00:20:10:02">But the solution,  some states are increasingly looking at involves suffocating prisoners  to death using nitrogen gas, something like most execution procedures  that wasn't developed medical professionals but originated  with a bunch of amateur death enthusiasts.</span>
            <span class="caption Source" data-start="00:20:23:22">It first found its way into US  law a few years back after this, Oklahoma state legislator watched a BBC documentary  called How to Kill a Human Being, in which a retired member of British  Parliament sampled various execution protocols before deciding that nitrogen  was the perfect killing device.</span>
            <span class="caption Joke" data-start="00:20:41:03">And look, there are lots of TV programs  you can learn from. Bill Nye The Science Guy can teach you  about science. The Kitchen can teach you  about cooking. And Property Brothers could teach you  how to renovate a house with your twin brother,  who you've definitely fucked.</span>
            <span class="caption Point" data-start="00:20:53:16">But lawmakers shouldn't be learning how to perform executions  from one. That legislator then called in this guy, a  high school friend of his and criminal justice professor who put together a presentation  for the legislature in which he tried to prove the method  was painless by, for some reason, playing YouTube videos of kids  passing out from breathing helium.</span>
            <span class="caption Source" data-start="00:21:14:11">So this is a teenager that is breathing helium  to make their voice sound funny, but they're not really thinking that when they're breathing helium,  they're not breathing oxygen. And so she's trying to get as big a breath  as she can, and in a second,  she becomes hypoxic. So then they get back up and they're  giggling and laughing. Now, obviously,  there's a lot wrong with that.</span>
            <span class="caption Explanation" data-start="00:21:53:08">For starters, those kids are voluntarily  depriving themselves of oxygen, not trying to resist, which is what would  likely happen during an execution. So you can't really compare  the two scenarios. But since Oklahoma lawmakers  seem to respond</span>
            <span class="caption Joke" data-start="00:22:04:01">well to videos of people on helium,  allow me to address them directly to deliver an important message  about that criminal justice professor. Here goes. Fuck that guy and he's fucking YouTube  videos. Stop listening to a man who doesn't know what the fuck  he's talking about, you idiot.</span>
            <span class="caption Point" data-start="00:22:26:13">I'll point out both the expert  and the legislator who brought him in lack what you would think would be  a pretty relevant bit of experience.</span>
            <span class="caption Source" data-start="00:22:35:14">Have you ever personally seen  an execution? No. I'm wondering,  have you ever been to an execution? Never have. And I don't wish to. Why's that. That's not my I probably should, but I have no wish or desire to witness one.</span>
            <span class="caption Explanation" data-start="00:22:51:16">Oh really? Why not Mike? Because killing another human being  is an act of brutality that's harrowing to witness?  Because being present might impress on you the hideous gravity of the power  you've given yourself?</span>
            <span class="caption Joke" data-start="00:23:01:16">Or were you just like super busy on the day  they were doing it?</span>
            <span class="caption Explanation" data-start="00:23:05:10">Look, if they consulted an actual expert,  they might have learned that even animal welfare guidelines  no longer allow pets to be put down with nitrogen gas because dogs are observed,  yelping, gasping and convulsing.</span>
            <span class="caption Point" data-start="00:23:15:18">Nevertheless, legislators in Oklahoma  voted to allow nitrogen gas executions, and apparently during the debate over it,  there were a few holdouts, but only because they didn't  want the inmate to feel good while dying. They wanted pain.</span>
            <span class="caption Point" data-start="00:23:28:17">And since Oklahoma's decision, multiple  other states have passed similar laws and early this year, Alabama performed  the very first nitrogen gas execution, which was, by all accounts,  absolutely horrific.</span>
            <span class="caption Source" data-start="00:23:40:04">One witness described the man who died  as someone struggling for their life and another who'd seen five executions said it was definitely  the most violent execution that I've ever witnessed. All of which makes it pretty galling  that afterwards the state's A.G. took this victory lap  while thanking his whole execution team. Everyone in this room knows  they are the first team in the country to carry out nitrogen execution.  And what occurred last night was textbook. They deserve a great deal of thanks  and credit for being willing to be the one to step up,  first in the country to do so. And I now suspect  that many states will follow. As of last night, nitrogen hypoxia as a means of execution,  is no longer an untested method. It is a proven one.</span>
            <span class="caption Explanation" data-start="00:24:24:14">Yeah, he called it a textbook execution,  which I would call textbook bullshit.</span>
            <span class="caption Joke" data-start="00:24:30:06">And by the way, Alabama, do you ever get  tired of being trailblazers in all of the worst ways? Your state history is just brave Alabama  citizens protesting, as your leaders are the last to do something good  or the first to do something terrible.</span>
            <span class="caption Point" data-start="00:24:43:19">And look, it seems America's  going to keep innovating ways to kill people and drawing a veil  around it to protect anyone involved. But on some level, all this secrecy is also meant to protect  us, the people in whose name it is done from confronting the horror  of what the death penalty truly is. Because whether it's nitrogen gas  or an IV injection of drugs or a firing squad or an electric chair or being pressed  with weights, it's all brutal. And to their credit,  some lawmakers will admit this.</span>
            <span class="caption Source" data-start="00:25:11:11">When Idaho was debating whether it should have a shield law  for supplies of its death penalty drugs, one state  senator summed it all up pretty well. There's a fundamental contradiction  at work here. Lethal injection, I believe,  is sold to the public as humane. And yet the secrecy that becomes necessary  in order to actually get and use the drugs mandates  that the public can't independently confirm  that it is, in fact, humane. And there is a great deal of evidence  to indicate that in at least some cases it is not. I think lethal injection is a lie. It is as if we are selling the idea that this is just  putting your pet to sleep. That's not what it is. And then in order to perpetuate that lie, we have to lie and lie and lie  and lie and lie again. This is a terrible position  to put our public servants in. It's a terrible position to put the state  of Idaho in. It's wrong, it's unfair. It needs to stop.</span>
            <span class="caption Explanation" data-start="00:26:14:07">He's right. It is, and it does. And lying is one of the first things  we teach our children not to do.</span>
            <span class="caption Joke" data-start="00:26:21:04">Then we tell them they'll be punished  by the tooth fairy and or Santa Claus. But that is trauma they can all work out later.</span>
            <span class="caption Point" data-start="00:26:27:02">The fact is, no matter how executions are performed, they'll never be humane, No matter how many times you call them  textbook or claim it's much better than anything they did to the victims or show people  viral videos of dizzy tweens on helium. It's never going to be okay. And we are kidding ourselves  if we think taking someone's life actually lowers  the number of killers in the world. It literally, definitionally, creates more.</span>
            <span class="caption Point" data-start="00:26:50:09">I know this is usually the point  where I say: so what can we do? But the answer is so  clearly, just stop doing it. The fact is, around the country,  there are still over 2300 people on death row. And I know in some cases they're in states  where no one in a position of power will put a stop to the execution. But when it comes to federal prisoners,  Biden could, before leaving office, commute  all 42 death sentences to life in prison. That way, even if Trump is reelected,  he can't pick the bing bong bloodbath up right where he left off. But beyond commuting sentences, Biden's  administration could do so much more it could investigate the legality of the federal government's drug purchases  from Absolute Standards and rescind that bullshit DOJ memo that tries  to exempt execution drugs from regulation. It could also force states  to surrender the pentobarbital that they've acquired from  an unregulated source. As for state legislatures,  I would argue they should be eliminating secrecy statutes,  not passing more of them. Because if the government is going to give itself the power  to execute its own citizens, which for the final time  I strongly believe that it should not, then I want to see where  the drugs come from, who's making them, and relentless scrutiny  of every part of this process, because all of this is being done  in our name and far too often in secret. And we should get a voice to express  exactly how we feel about that.</span>
            <span class="caption Joke" data-start="00:28:07:05">Specifically, this voice. Stop fucking  killing people, you fucking assholes.</span>            


        </p>
    </div>
</Slide>

<style>

    .content {
        margin: auto;
    }
    
    .sticky {
        position: fixed;     /* Fix the position relative to the viewport */
        top: 50%;            /* Position it 50% from the top */
        left: 50%;           /* Position it 50% from the left */
        transform: translate(-50%, -50%); /* Center it by adjusting its own dimensions */
        background-color: #f1f1f186;
        /* border: 1px black solid; */
        padding: 50px;
        font-size: 4em;
        color: #494949;
        z-index: 1; /* Ensure it's on top of other elements */
    }


    .transcript {
        display: block;
        position: static;
        font-size: 12px;
        z-index: -1;
        overflow: hidden;
        text-align: justify;
        color:#6f6f6f
    }

    /* .Joke {
        background-color: #FFADAD;
    } */
</style>